# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\logs.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(928, 683)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tbl_logs = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl_logs.setGeometry(QtCore.QRect(0, 50, 921, 591))
        self.tbl_logs.setObjectName("tbl_logs")
        self.tbl_logs.setColumnCount(3)
        self.tbl_logs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_logs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_logs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_logs.setHorizontalHeaderItem(2, item)
        self.tbl_logs.horizontalHeader().setDefaultSectionSize(306)
        self.tbl_logs.verticalHeader().setVisible(False)
        self.dttmStart = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dttmStart.setGeometry(QtCore.QRect(10, 20, 121, 22))
        self.dttmStart.setObjectName("dttmStart")
        self.dttmEnd = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dttmEnd.setGeometry(QtCore.QRect(140, 20, 121, 22))
        self.dttmEnd.setObjectName("dttmEnd")
        self.chk_now = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_now.setGeometry(QtCore.QRect(270, 20, 61, 20))
        self.chk_now.setObjectName("chk_now")
        self.chk_info = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_info.setGeometry(QtCore.QRect(330, 20, 61, 20))
        self.chk_info.setObjectName("chk_info")
        self.chk_warn = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_warn.setGeometry(QtCore.QRect(390, 20, 61, 20))
        self.chk_warn.setObjectName("chk_warn")
        self.chk_error = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_error.setGeometry(QtCore.QRect(460, 20, 71, 20))
        self.chk_error.setObjectName("chk_error")
        self.btn_refresh = QtWidgets.QPushButton(self.centralwidget)
        self.btn_refresh.setGeometry(QtCore.QRect(820, 10, 93, 28))
        self.btn_refresh.setObjectName("btn_refresh")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 0, 21, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 0, 21, 16))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 928, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tbl_logs.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Дата"))
        item = self.tbl_logs.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Тип"))
        item = self.tbl_logs.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Сообщение"))
        self.chk_now.setText(_translate("MainWindow", "Now"))
        self.chk_info.setText(_translate("MainWindow", "INFO"))
        self.chk_warn.setText(_translate("MainWindow", "WARN"))
        self.chk_error.setText(_translate("MainWindow", "ERROR"))
        self.btn_refresh.setText(_translate("MainWindow", "Обновить"))
        self.label.setText(_translate("MainWindow", "От"))
        self.label_2.setText(_translate("MainWindow", "До"))
