# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2560, 1440)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bar_frame = QtWidgets.QFrame(self.centralwidget)
        self.bar_frame.setGeometry(QtCore.QRect(10, 10, 2541, 391))
        self.bar_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bar_frame.setObjectName("bar_frame")
        self.bar_label = QtWidgets.QLabel(self.bar_frame)
        self.bar_label.setGeometry(QtCore.QRect(0, 0, 2541, 391))
        self.bar_label.setText("")
        self.bar_label.setObjectName("bar_label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(1490, 410, 1051, 471))
        self.frame.setStyleSheet("background: rgb(255, 255, 255)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bunker_info = QtWidgets.QFrame(self.centralwidget)
        self.bunker_info.setGeometry(QtCore.QRect(10, 410, 1451, 971))
        self.bunker_info.setStyleSheet("background: rgb(255, 255, 255)")
        self.bunker_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bunker_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bunker_info.setObjectName("bunker_info")
        self.qnt_graph = QtWidgets.QFrame(self.bunker_info)
        self.qnt_graph.setEnabled(True)
        self.qnt_graph.setGeometry(QtCore.QRect(20, 20, 1411, 931))
        self.qnt_graph.setStyleSheet("background: rgb(207, 207, 207)")
        self.qnt_graph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.qnt_graph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.qnt_graph.setObjectName("qnt_graph")
        self.close_bunker = QtWidgets.QPushButton(self.bunker_info)
        self.close_bunker.setEnabled(True)
        self.close_bunker.setGeometry(QtCore.QRect(0, 0, 21, 28))
        self.close_bunker.setObjectName("close_bunker")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(1490, 910, 1051, 471))
        self.frame_2.setStyleSheet("background: rgb(255, 255, 255)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2560, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.close_bunker.setText(_translate("MainWindow", "<"))
