# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\process.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(462, 604)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_dbConnected_name = QtWidgets.QLabel(self.centralwidget)
        self.lbl_dbConnected_name.setGeometry(QtCore.QRect(20, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_dbConnected_name.setFont(font)
        self.lbl_dbConnected_name.setObjectName("lbl_dbConnected_name")
        self.lbl_hardwareConnected_name = QtWidgets.QLabel(self.centralwidget)
        self.lbl_hardwareConnected_name.setGeometry(QtCore.QRect(250, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_hardwareConnected_name.setFont(font)
        self.lbl_hardwareConnected_name.setObjectName("lbl_hardwareConnected_name")
        self.lbl_dbConnected_value = QtWidgets.QLabel(self.centralwidget)
        self.lbl_dbConnected_value.setGeometry(QtCore.QRect(180, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_dbConnected_value.setFont(font)
        self.lbl_dbConnected_value.setText("")
        self.lbl_dbConnected_value.setObjectName("lbl_dbConnected_value")
        self.lbl_hardwareConnected_value = QtWidgets.QLabel(self.centralwidget)
        self.lbl_hardwareConnected_value.setGeometry(QtCore.QRect(410, 10, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_hardwareConnected_value.setFont(font)
        self.lbl_hardwareConnected_value.setText("")
        self.lbl_hardwareConnected_value.setObjectName("lbl_hardwareConnected_value")
        self.tbl_loadQueue = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl_loadQueue.setGeometry(QtCore.QRect(0, 60, 461, 491))
        self.tbl_loadQueue.setObjectName("tbl_loadQueue")
        self.tbl_loadQueue.setColumnCount(2)
        self.tbl_loadQueue.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_loadQueue.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_loadQueue.setHorizontalHeaderItem(1, item)
        self.tbl_loadQueue.horizontalHeader().setDefaultSectionSize(229)
        self.tbl_loadQueue.verticalHeader().setVisible(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 462, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_dbConnected_name.setText(_translate("MainWindow", "Database connected:"))
        self.lbl_hardwareConnected_name.setText(_translate("MainWindow", "Hardware connected:"))
        item = self.tbl_loadQueue.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Идентификатор"))
        item = self.tbl_loadQueue.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Источник"))
