"""add process model

Revision ID: 083abf28d81c
Revises: 4771f4b6820e
Create Date: 2023-03-24 21:07:29.547650

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '083abf28d81c'
down_revision = '4771f4b6820e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('process',
    sa.Column('start_dttm', sa.DateTime(timezone=True), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('process_id'),
    schema='ddl'
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('process', schema='ddl')
    # ### end Alembic commands ###
