"""add logs

Revision ID: 30461ed43d76
Revises: e26bccc66116
Create Date: 2023-05-03 23:53:37.302802

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '30461ed43d76'
down_revision = 'e26bccc66116'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('logs_process_id_fkey', 'logs', schema='ddl', type_='foreignkey')
    op.drop_column('logs', 'process_id', schema='ddl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('process_id', sa.INTEGER(), autoincrement=False, nullable=False), schema='ddl')
    op.create_foreign_key('logs_process_id_fkey', 'logs', 'process', ['process_id'], ['process_id'], source_schema='ddl', referent_schema='ddl')
    # ### end Alembic commands ###
