"""add process model

Revision ID: 313663926ca4
Revises: 083abf28d81c
Create Date: 2023-03-24 21:28:19.622826

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '313663926ca4'
down_revision = '083abf28d81c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('alumina_feed',
    sa.Column('feed_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bunker_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bunker_id'], ['ddl.bunker.bunker_id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['ddl.process.process_id'], ),
    sa.PrimaryKeyConstraint('feed_dt', 'bunker_id'),
    schema='ddl'
    )
    op.create_table('alumina_load',
    sa.Column('load_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bunker_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bunker_id'], ['ddl.bunker.bunker_id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['ddl.process.process_id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['ddl.alumina_type.type_id'], ),
    sa.PrimaryKeyConstraint('load_dt', 'bunker_id', 'type_id'),
    schema='ddl'
    )
    op.create_table('bunker_state',
    sa.Column('measure_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bunker_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('is_estimate', sa.Boolean(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bunker_id'], ['ddl.bunker.bunker_id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['ddl.process.process_id'], ),
    sa.PrimaryKeyConstraint('measure_dt', 'bunker_id'),
    schema='ddl'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bunker_state', schema='ddl')
    op.drop_table('alumina_load', schema='ddl')
    op.drop_table('alumina_feed', schema='ddl')
    # ### end Alembic commands ###
