"""add process model

Revision ID: 4771f4b6820e
Revises: 9346bd628974
Create Date: 2023-03-24 20:26:09.751702

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4771f4b6820e'
down_revision = '9346bd628974'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process',
    sa.Column('start_dttm', sa.DateTime(timezone=True), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('start_dttm', 'process_id'),
    schema='ddl'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process', schema='ddl')
    # ### end Alembic commands ###
