"""add feed and load id

Revision ID: 797a78d9c7fd
Revises: 433517ea3ea2
Create Date: 2023-04-01 19:14:55.125434

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '797a78d9c7fd'
down_revision = '433517ea3ea2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumina_feed',
    sa.Column('feed_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('bunker_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bunker_id'], ['ddl.bunker.bunker_id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['ddl.process.process_id'], ),
    sa.PrimaryKeyConstraint('feed_id'),
    schema='ddl'
    )
    op.create_table('alumina_load',
    sa.Column('load_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.Column('bunker_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('source_bunker_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bunker_id'], ['ddl.bunker.bunker_id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['ddl.process.process_id'], ),
    sa.ForeignKeyConstraint(['source_bunker_id'], ['ddl.bunker.bunker_id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['ddl.alumina_type.type_id'], ),
    sa.PrimaryKeyConstraint('load_id'),
    schema='ddl'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alumina_load', schema='ddl')
    op.drop_table('alumina_feed', schema='ddl')
    # ### end Alembic commands ###
