"""make bunker deleted_flg

Revision ID: 919a9af960c9
Revises: f20945d2462c
Create Date: 2023-05-03 20:22:08.469174

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '919a9af960c9'
down_revision = 'f20945d2462c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('penis', schema='rep')
    op.add_column('bunker', sa.Column('deleted_flg', sa.Boolean(), nullable=True), schema='ddl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bunker', 'deleted_flg', schema='ddl')
    op.create_table('penis',
    sa.Column('hui', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.UniqueConstraint('hui', name='a'),
    schema='rep'
    )
    # ### end Alembic commands ###
