"""add logs

Revision ID: c914ea9a373d
Revises: 919a9af960c9
Create Date: 2023-05-03 21:39:40.230465

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c914ea9a373d'
down_revision = '919a9af960c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('log_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('log_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('log_id'),
    schema='ddl'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs', schema='ddl')
    # ### end Alembic commands ###
