"""add logs

Revision ID: e26bccc66116
Revises: c914ea9a373d
Create Date: 2023-05-03 21:46:18.217665

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e26bccc66116'
down_revision = 'c914ea9a373d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('process_id', sa.Integer(), nullable=False), schema='ddl')
    op.create_foreign_key(None, 'logs', 'process', ['process_id'], ['process_id'], source_schema='ddl', referent_schema='ddl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logs', schema='ddl', type_='foreignkey')
    op.drop_column('logs', 'process_id', schema='ddl')
    # ### end Alembic commands ###
