"""add feed and load id

Revision ID: f20945d2462c
Revises: 797a78d9c7fd
Create Date: 2023-04-01 19:16:00.714414

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f20945d2462c'
down_revision = '797a78d9c7fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumina_load', 'source_bunker_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='ddl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumina_load', 'source_bunker_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='ddl')
    # ### end Alembic commands ###
